# Generated by Django 4.1.7 on 2023-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='search_max_playlist_videos',
            field=models.IntegerField(default=1, help_text='Maximum amoount of videos per playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='search_max_playlists',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='search_max_video_length',
            field=models.IntegerField(default=1, help_text='Maximum length for a video in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='snippets_max_length',
            field=models.IntegerField(default=1, help_text='Maximum length of a video snippet in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='snippets_monthly_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='summaries_max_video_length',
            field=models.IntegerField(default=1, help_text='Maximum length for a video to summarise in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='summaries_monthly_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
