# Generated by Django 4.1.7 on 2023-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscriptionplan_monthly_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='monthly_limit',
            new_name='search_playlists_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='monthly_usage',
        ),
        migrations.AddField(
            model_name='subscription',
            name='snippets_usage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='summaries_usage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
