# Generated by Django 4.1.7 on 2023-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_monthly_limit_subscription_search_playlists_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='search_playlists_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='snippets_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='summaries_usage',
            field=models.IntegerField(default=0),
        ),
    ]
