# Generated by Django 4.1.7 on 2023-03-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusermodel_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='active',
            new_name='is_active',
        ),
    ]
