# Generated by Django 4.1.7 on 2023-03-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_active_customusermodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='created_on',
            new_name='date_joined',
        ),
    ]
