# Generated by Django 4.1.7 on 2023-03-30 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_on_customusermodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 18, 1, 1, 201597, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 18, 1, 1, 201597, tzinfo=datetime.timezone.utc)),
        ),
    ]
