# Generated by Django 4.1.7 on 2023-03-30 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customusermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 18, 2, 26, 879598, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 18, 2, 26, 879598, tzinfo=datetime.timezone.utc)),
        ),
    ]
