# Generated by Django 4.1.7 on 2023-03-31 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customusermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
