# Generated by Django 4.1.7 on 2023-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customusermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
