# Generated by Django 4.1.7 on 2023-03-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_snippet_end_snippet_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary_text',
        ),
    ]
