# Generated by Django 4.1.7 on 2023-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_summary_summary_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='bullet_points',
            field=models.TextField(),
        ),
    ]
