# Generated by Django 4.1.7 on 2023-05-06 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0004_alter_snippet_text_alter_summary_bullet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.youtubevideo'),
        ),
    ]
