# Generated by Django 4.1.7 on 2023-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_summary_date_created_summary_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='length',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
